### ISSUE TITLE
Transferring repo

### ISSUE THREAD

**Issue by orschiro** [orschiro/simple-translate#12]
Dear @Grabli66, 
dear @JerryCasiano,

I am cleaning up my repositories (I have way too many).

May I transfer this repo to one of you?

Thanks!

-Robert

**Comment by JerryCasiano** [comment]
Sorry to say that I have little time these days. So, it would just sit.

**Comment by orschiro** [comment]
No problem, @JerryCasiano.

@Grabli66 what about you?

**Comment by Grabli66** [comment]
Ok. You can transfer it to me.

**Comment by orschiro** [comment]
Done, thank you so much @Grabli66! :-)
