### ISSUE TITLE
Window border

### ISSUE THREAD

**Issue by Grabli66** [orschiro/simple-translate#3]
White border on ubuntu is looking ugly

**Comment by orschiro** [comment]
![image](https://cloud.githubusercontent.com/assets/170947/15281550/96bd8082-1b3c-11e6-8997-6e809ecfe0b4.png)

**Comment by Grabli66** [comment]
Fixed

**Comment by orschiro** [comment]
Thanks @Grabli66!

Is this already part of the recompiled deb packages?

~Robert

**Comment by Grabli66** [comment]
Yes

2016-06-01 8:29 GMT+03:00 Robert Orzanna notifications@github.com:

**Comment by orschiro** [comment]
Then I probably just didn't receive the update yet: `0.9.4-0~8~ubuntu16.04.1`
