### ISSUE TITLE
Recompile deb packages?

### ISSUE THREAD

**Issue by orschiro** [orschiro/simple-translate#6]
Dear @Grabli66,

Would it be possible to recompile the deb packages in your PPA?

Warmly,

~Robert

**Comment by Grabli66** [comment]
Yes, of course.

2016-05-19 10:55 GMT+03:00 Robert Orzanna notifications@github.com:

**Comment by orschiro** [comment]
Great, thanks! :+1: 

~Robert

**Comment by Grabli66** [comment]
I don't forget about deb packaging. But i have some problem with that, damn
launchpad don't build it. I'll fix that, but later.

2016-05-19 13:47 GMT+03:00 Robert Orzanna notifications@github.com:

**Comment by orschiro** [comment]
Do you need any help with the built process?

~Robert

**Comment by Grabli66** [comment]
Hi.
Sorry that i not answered. It's all my work.
I'll do it by myself. I need more time.

2016-05-20 15:18 GMT+03:00 Robert Orzanna notifications@github.com:

**Comment by orschiro** [comment]
Dear @Grabli66, 

Sure, please do take the time you need!

Warmly,

~Robert

**Comment by Grabli66** [comment]
Recompiled
