### ISSUE TITLE
Broken icons?

### ISSUE THREAD

**Issue by orschiro** [orschiro/simple-translate#8]
Dear all, 

Can someone confirm suddenly broken icons?

Screenshot from Ubuntu 16.04:

![image](https://cloud.githubusercontent.com/assets/170947/15565596/123fc256-231c-11e6-9c10-daaa8a21b8e2.png)

Thankfully,

~Robert

**Comment by Grabli66** [comment]
I broke it :)
I at last created ppa package, but broke icons.
I'll fix it.

2016-05-26 9:30 GMT+03:00 Robert Orzanna notifications@github.com:

**Comment by orschiro** [comment]
No worries! :smile: 

I just wanted to make sure that it actually came from a new update. 

Thankfully,

~Robert

**Comment by orschiro** [comment]
Seems to be fixed again. 

Thanks @Grabli66! :+1: 

![image](https://cloud.githubusercontent.com/assets/170947/15642910/8ac5cd48-264a-11e6-96b4-3084df97e254.png)

**Comment by Grabli66** [comment]
Yes. I fix it some days ago.

2016-05-30 10:40 GMT+03:00 Robert Orzanna notifications@github.com:
