### ISSUE TITLE
Files generated above project folder

### ISSUE THREAD

**Issue by JerryCasiano** [orschiro/simple-translate#9]
https://github.com/orschiro/simple-translate/commit/321384890a43c5dbf4989ed9cca985e1e6ae0b85

Introduced a small bug where files generated during configuration are created above the project directory. i.e.

configure_file (src/Main.vala.in ../src/Main.vala)

The ../ causes a folder src to be created outside the project directory and the resulting Main.vala is placed there.

Also, any files listed in a configure_file() should be removed from version control since they're generated by cmake.

**Comment by orschiro** [comment]
Thanks for the bug report, @JerryCasiano! 

Your detailed description looks like something to practise coding with. 

Maybe I will manage to resolve this. :smile: 

Warmly,

~Robert

**Comment by Grabli66** [comment]
If files generated outside of src folder, the launchpad can't find them
when builds deb package.
I'll add to gitignore generated files

2016-06-02 7:08 GMT+03:00 Robert Orzanna notifications@github.com:

**Comment by JerryCasiano** [comment]
Merging the last PR took care of this issue.
